version: "3.9"

services:
  qdrant:
    image: qdrant/qdrant
    ports:
      - "6333:6333"
    volumes:
      - ./qdrant-data:/qdrant/storage

  mssql:
      image: mcr.microsoft.com/mssql/server:2022-latest
      container_name: mssql
      environment:
        - MSSQL_SA_PASSWORD=Pass.123!
        - ACCEPT_EULA=Y
      ports:
        - 1433:1433
      volumes:
        - ./sqlserver/data:/var/opt/mssql/data